http:
 port: "8082"
 
s3:
 accessKey: "AKIA4CK3TPJXUD6UY7PL"
 secretAccessKey: "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"
 bucketName: "tell-me-you-love-me"
 
path:
 in: "D:/AnypointStudioWorkspace/mule_with_aws/src/main/resources/in"